version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/cicdproject
permissions:
  - object: /home/ec2-user/cicdproject/
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: /home/ec2-user/cicdproject/scripts/deploy.sh
      timeout: 60
      runas: ec2-user

permissions:
  - object: /home/ec2-user/cicdproject/scripts/deploy.sh
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
